fear: adding redux to history
lucasabot/bloc-de-notas pull request #3
Opened 2022-01-20 14:16 UTC by lucasabot

# Adding redux to history

### New layout version

![image](https://user-images.githubusercontent.com/96079880/150354282-64f51af9-d452-446e-95af-387dbdd00044.png)

### By pressing the new save button we will dispatch a new note or changes to the redux state

![image](https://user-images.githubusercontent.com/96079880/150354403-e14722d4-a78f-4ff7-baf3-2e018444e893.png)
 
 ### We can check the notes history located in redux at the "history" section 
 
![image](https://user-images.githubusercontent.com/96079880/150355357-5a1db014-a0d2-4121-ac8f-ecdbec9fabd4.png)

2022-01-20 18:58 UTC, facu-rodriguez requested changes
Nice work Abot!!

some comments.

- I believe we shouldn't let the user to save an empty note. To save a note we should have a title and something on the body. Anyway, we can disscus it!

https://user-images.githubusercontent.com/68086087/150373473-23bc7dc6-875e-4cb2-b185-87b6fd59e983.mp4

If we don't validate that the note isn't empty this kind of things could happen


https://user-images.githubusercontent.com/68086087/150374797-dc18b16b-3e81-4916-b18f-a819e4edb426.mp4

- After validating this, in history view, the user shouldn't be able to save an empty note, or a note without title o text.

---------------------------------

The ButtonContainer component has an empty utils.js file, delete it.

---------------------------------

2022-01-20 18:58 UTC, facu-rodriguez commented on src/app/components/InlineTextArea/index.js
>      inputRef.current.setSelectionRange(value.length, value.length); // Setea el cursor al final
remember to delete these coments!

2022-01-20 18:58 UTC, facu-rodriguez commented on src/app/components/InlineTextArea/index.js
>  import MagicButton from '../MagicButton';
we should be consistent in the way we import the components.

2022-01-20 18:58 UTC, facu-rodriguez commented on src/app/components/InlineTextArea/index.js
> +const CustomTextArea = ({ value, placeholder, classNames, toggle, onBlur, ...others }) => {
we shouldn't have two components in the same component file, please, separate them.

2022-01-20 18:58 UTC, facu-rodriguez commented on src/app/components/InlineTextArea/index.js
>        },
we usually write functions inside a utils.js file

2022-01-20 18:58 UTC, facu-rodriguez commented on src/app/components/InlineTextArea/index.js
> +          addToast(`Se guardo la nota correctamente.`);
Import this text from the text file using i18

2022-01-20 18:58 UTC, facu-rodriguez commented on src/app/components/InlineTextArea/styles.module.scss
> +  background-color: rgba(84, 140, 255, 0.6) !important;
Add this color into colors.scss file and import it from there

2022-01-20 18:58 UTC, facu-rodriguez commented on src/app/components/InlineTextArea/styles.module.scss
> +  padding: 0 3px 0 3px;
In these cases there is no need to write the 4 values
```suggestion
  padding: 0 3px;
```

2022-01-20 18:58 UTC, facu-rodriguez commented on src/app/components/InlineTextArea/styles.module.scss
> +  // margin-left: auto;
delete this

2022-01-20 18:58 UTC, facu-rodriguez commented on src/app/components/InlineTextArea/styles.module.scss
>    border: none;
Re order this props

2022-01-20 18:58 UTC, facu-rodriguez commented on src/app/components/InlineTextArea/styles.module.scss
>    box-shadow: inset 0px 0px 0px 1px $primary-button;
re order this props

2022-01-20 18:58 UTC, facu-rodriguez commented on src/app/components/InlineTextArea/styles.module.scss
> +  box-shadow: inset 0px 0px 0px 1px #548cff;
#548cff color should be  imported from colors.scss file

2022-01-20 18:58 UTC, facu-rodriguez commented on src/app/components/InlineTextArea/utils.js
>  export const buttonsArray = [
if this array doesn't has any logic or doesn't call any function inside we should leave it on a constants.js file

2022-01-20 18:58 UTC, facu-rodriguez commented on src/app/components/MagicButton/index.js
> +const MagicButton = ({ buttonText, onClick, className = '', ...others }) => (
Change the component name to "NoteButton" or something like that

2022-01-20 18:58 UTC, facu-rodriguez commented on src/app/components/Topbar/index.js
> +        disabled={[HOME, '/home'].includes(pathName)}
extract this logic into a function that could receive the button route as a parameter so then you can call it any time you need to check if it should be disabled or not

2022-01-20 18:58 UTC, facu-rodriguez commented on src/app/components/InlineInput/index.js
>      // eslint-disable-next-line
why is this here?

2022-01-20 18:58 UTC, facu-rodriguez commented on src/app/components/Topbar/styles.module.scss
> +  font-size: $small * 0.9 !important;
why not just define the size?

2022-01-20 18:58 UTC, facu-rodriguez commented on src/app/components/Topbar/styles.module.scss
> +  margin: 0px 3px 0px 3px;
Same as above

2022-01-20 18:58 UTC, facu-rodriguez commented on src/app/screens/Bloc/index.js
> +const Bloc = ({ dispatch }) => {
Instead of using the connect just for use a dispatch use the "useDispatch" hook

2022-01-20 18:58 UTC, facu-rodriguez commented on src/app/screens/Bloc/index.js
> +  };
Remember that you should use () instead of {} when you return the value directly

2022-01-20 18:58 UTC, facu-rodriguez commented on src/app/screens/Bloc/index.js
>    const handleTitleChange = e => {
same as above

2022-01-20 18:58 UTC, facu-rodriguez commented on src/app/screens/Bloc/index.js
>      setTextValue(e.target.value);
same as above

2022-01-20 18:58 UTC, facu-rodriguez commented on src/app/screens/History/components/NoteItem/index.js
> +  };
same as above

2022-01-20 18:58 UTC, facu-rodriguez commented on src/app/screens/History/components/NoteItem/index.js
> +    addToast('Se borro la nota correctamente.', { style: 'danger' });
import this text from text file using i18

2022-01-20 18:58 UTC, facu-rodriguez commented on src/app/screens/History/components/NoteItem/styles.module.scss
> +  margin: 6px 3px 6px 3px;
same as above
```suggestion
  margin: 6px 3px;
```

2022-01-20 18:58 UTC, facu-rodriguez commented on src/app/screens/History/components/NoteItem/styles.module.scss
> +/* On mouse-over, add a deeper shadow */
delete this

2022-01-20 18:58 UTC, facu-rodriguez commented on src/app/screens/History/components/NoteItem/styles.module.scss
> +.noteItem_text_textArea {
Extract the common styles properties into a class and then extend it whenever you need those properties

For example:
`font-size: $medium !important;`
`max-width: 100% !important;`
`min-height: 0 !important;`

2022-01-20 18:58 UTC, facu-rodriguez commented on src/app/screens/History/components/NoteItem/utils.js
> +      : `El campo ${fields[0]} esta vacio, desea salvar este cambio?`
move this texts into text file

2022-01-20 18:58 UTC, facu-rodriguez commented on src/app/screens/History/components/NotesContainer/index.js
> +import React from 'react';
delete the empty constants file on NotesContainer component

2022-01-20 18:58 UTC, facu-rodriguez commented on src/app/screens/History/index.js
>  const History = () => {
```suggestion
const History = () => (
    <div className={styles.container}>
      <UTLabel bold large black>
        {i18.t('History:title')}
      </UTLabel>
      <NotesContainer notes={useSelector(getNotesSelector)} />
    </div>
  );

```

2022-01-20 18:58 UTC, facu-rodriguez commented on src/config/someCustomer/texts.js
> +    },
```suggestion
    History: {
      title: 'Historial',
      empty: 'No hay notas guardadas.'
    },
```

2022-01-20 18:58 UTC, facu-rodriguez commented on src/utils/functionUtils.js
> + *  y devuelve un arreglo con el resultado de agregar o retirar el estilo que recibio */
delete all comments in this file

2022-01-20 18:58 UTC, facu-rodriguez commented on src/redux/notes/selectors.js
> +);
since we are just using this selector in only 1 component, delete this file and create the selector directly in the component

2022-01-21 22:03 UTC, fperezboco requested changes
Excellent Job Abot!! Some tiny details.

- Check you have an empty utils.js in ButtonContainer component.
- Check you have an empty styles.module.scss in CustomTextArea

2022-01-21 22:03 UTC, fperezboco commented on src/app/components/ButtonContainer/styles.module.scss
>    width: 30rem;
Order props

2022-01-21 22:03 UTC, fperezboco commented on src/app/components/Topbar/index.js
> +        onPress={goToHome}
Another option would have been to create an array like
```
const options = [
  {
    onPress: goToHome
    disabled: ...
    label: ...
  },
  etc
]
```

And then do options.map(...) returning an UTButton for each. In that way, you avoid repeating UTButton and styles.topBarButton

2022-01-21 22:03 UTC, fperezboco commented on src/app/components/Topbar/styles.module.scss
> +    width: 30%;
We generally try to avoid non 100% relative values. It gets a bit unpredictable.

2022-01-21 22:03 UTC, fperezboco commented on src/app/components/Topbar/utils.js
> + * checkButtonDisabled - verifica si el segundo argumento (currentPath) coincide o esta incluido en el primer argumento (buttonPath)
remove comments

2022-01-21 22:03 UTC, fperezboco commented on src/app/screens/History/components/NoteItem/index.js
> +      <NotepadButton buttonText="X" onClick={handleSelfDelete} className={styles.noteItem_deleteButton} />
Move X to constants

2022-01-21 22:03 UTC, fperezboco commented on src/app/screens/History/components/NotesContainer/index.js
> +      <UTLabel className={styles.notesContainer_emptyMsg} medium gray>
don't mix camel case with snake case

2022-01-21 22:03 UTC, fperezboco commented on src/app/screens/History/components/NotesContainer/style.module.scss
> +  width: 55%;
avoid non 100% values

2022-01-21 22:03 UTC, fperezboco commented on src/app/screens/History/index.js
> +import UTLabel from '@widergy/energy-ui/dist/components/UTLabel';
import { UTLabel } from '@widergy/energy-ui' is preferred so you can import multiple components in one line

2022-01-21 22:03 UTC, fperezboco commented on src/utils/contexts/ToastContext/index.js
> +export const ToastContextProvider = ({ children }) => {
Nice provider!

2022-01-21 22:03 UTC, fperezboco commented on src/utils/hooks/useToastContext.js
> +
this file shouldn't be in utils

2022-01-25 12:24 UTC, fperezboco requested changes
Great job Abot!! :muscle: some tiny details:

Why buttons are disabled? If you decide to disable them (I think it's a weird experience) it should be more consistent.

Buttons are disabled on main text area but not on title edition
![image](https://user-images.githubusercontent.com/78354349/150975911-83d286fe-3c0a-4e48-8ada-9443ce4dc2b7.png)

Why red button is not disabled?
![image](https://user-images.githubusercontent.com/78354349/150976074-a9162676-321f-456a-ad01-21bfca58b3e1.png)

Here I would remove border radius
![image](https://user-images.githubusercontent.com/78354349/150976270-0ab95512-3f30-4925-ad1c-28944ac5ff57.png)

2022-01-25 12:43 UTC, facu-rodriguez requested changes
Much better! Almost done!!

Check this out. 

- We shuoldn't let the user apply styles to the placeholder (same happens on /bloc-de-notas):

https://user-images.githubusercontent.com/68086087/150973725-38c0fdc2-93ca-46af-9b11-1f0ccb2a948c.mp4

-----------------------------------------------

- The bold style isn't showing even though the in the store was saved correctly.
- Same happens when trying to apply bold on the /history view and saving the note. Then, when going to another view an coming back, the thex doesn't appear with the style applied.

![Captura de pantalla de 2022-01-25 09-07-17](https://user-images.githubusercontent.com/68086087/150974329-4372e642-b38f-4b66-a9f9-c5d277ee67dc.png)

https://user-images.githubusercontent.com/68086087/150974321-55dcdbfc-4a23-4d15-80eb-dc7a44cc9a70.mp4

-------------------------------------------

- Delete this empty file
 src/redux/notes/selectors.js

2022-01-25 12:43 UTC, facu-rodriguez commented on src/app/components/CustomTextArea/constants.js
> +export { TEXTAREA_COLS, TEXTAREA_ROWS };
```suggestion
export const TEXTAREA_ROWS = 10;
export const TEXTAREA_COLS = 30;
```

2022-01-25 12:43 UTC, facu-rodriguez commented on src/app/components/CustomTextArea/styles.module.scss
> +  font-size: $large * 2;
remember to set exact values!

2022-01-25 12:43 UTC, facu-rodriguez commented on src/app/components/CustomTextArea/styles.module.scss
> +}
linter asks for an empty line on every file so add it!

2022-01-25 12:43 UTC, facu-rodriguez commented on src/app/components/NotepadButton/styles.module.scss
> +  padding: $medium/3 $medium !important;
same as above, define the sizes.

2022-01-25 12:43 UTC, facu-rodriguez commented on src/app/screens/History/components/NoteItem/styles.module.scss
> +      padding: $medium/6 $medium/2 !important;
same as above

2022-01-25 12:43 UTC, facu-rodriguez commented on src/config/someCustomer/texts.js
> +        emptyText: 'El titulo no puede estar vacio'
we are using these? if not please delete it

2022-01-25 14:30 UTC, fperezboco approved these changes
:ok_hand: Great job Abot!

For next PR, as we discussed, consider adding an object like this:
![image](https://user-images.githubusercontent.com/78354349/150995662-0196ca91-a7f8-4fc3-83ea-36b3be636189.png)

And round this
![image](https://user-images.githubusercontent.com/78354349/150995562-e8f85757-3d51-4cbf-afe4-14ecad41a8b5.png)

2022-01-25 15:06 UTC, facu-rodriguez approved these changes
nice!

2022-01-25 15:07 UTC, merged