feat: Services implementation
lucasabot/bloc-de-notas pull request #4
Opened 2022-01-24 19:43 UTC by lucasabot

# Now Redux actions request the services of [Training API](https://notes-api-for-practicing.herokuapp.com/api/notes)

![image](https://user-images.githubusercontent.com/96079880/150852686-371b5dac-1e05-412d-9b44-c4b2f3d7c159.png)

![image](https://user-images.githubusercontent.com/96079880/150852787-05b81d47-fefc-4531-b06a-cf9418f74149.png)

![image](https://user-images.githubusercontent.com/96079880/150852827-2c909c28-56f6-4f69-bb3f-bfce6f58b091.png)

2022-01-25 14:06 UTC, facu-rodriguez requested changes
Nice work!

Some comments.

- Disabled the button if the request is loading, otherwise this happens

https://user-images.githubusercontent.com/68086087/150990187-79ac275c-1200-437c-90c4-9a04de471edc.mp4

2022-01-25 14:06 UTC, facu-rodriguez commented on src/app/screens/History/components/NoteItem/index.js
> +      <NotepadButton buttonText="X" onClick={handleSelfDelete} className={styles.noteItem_deleteButton} />
use camel case

2022-01-25 14:06 UTC, facu-rodriguez commented on src/scss/variables/_mediaQueries.scss
> +$customMobile: 'only screen and (max-width : 900px)';
we shouldn't add any new mediaquerie!

2022-01-25 14:06 UTC, facu-rodriguez commented on src/app/screens/History/components/NotesContainer/style.module.scss
> +  @media #{$customMobile} {
check my comment about mediaqueries

2022-01-25 14:06 UTC, facu-rodriguez commented on src/app/screens/History/components/NotesContainer/style.module.scss
> +}
add an empty line

2022-01-25 14:06 UTC, facu-rodriguez commented on src/redux/notes/actions.js
> +  deleteInRedux: payload => ({ type: actions.DELETE_IN_REDUX, payload })
well done!

2022-01-25 14:06 UTC, facu-rodriguez commented on src/redux/notes/selectors.js
delete this file

2022-01-25 14:06 UTC, facu-rodriguez commented
checkout the conflicts!

2022-01-26 12:26 UTC, fperezboco requested changes
Nice job Abot! Some details to consider and improve the app:

---
On note save, if service fails, a wrong success message is shown
![test2](https://user-images.githubusercontent.com/78354349/151161819-6a725e32-89aa-42bc-9846-a42abb33a3dd.gif)
you can block services on Inspector>Network tab>right button on service>block request (remember to unblock it later)

---
Same for delete
![test3](https://user-images.githubusercontent.com/78354349/151162191-8b6e11f7-f436-4c57-85bf-cdab4870ff12.gif)

2022-01-26 12:26 UTC, fperezboco commented on src/app/components/InlineTextArea/index.js
> +            className={`${styles.span} ${styles.spanFontSizeMedium} ${styles.spanSizer} ${calcTextClassNames(
where is this span style?

2022-01-26 12:26 UTC, fperezboco commented on src/app/components/InlineTextArea/index.js
> +            {`${value || placeholder}`}
yo don't need `${}` here

2022-01-26 12:26 UTC, fperezboco commented on src/app/components/InlineTextArea/index.js
> +        <span className={`${styles.wordsQuantitySpan} `}>{`${i18.t(
remove white space

2022-01-26 12:26 UTC, fperezboco commented on src/app/components/InlineTextArea/index.js
>          )}: ${wordsQuantity}`}</span>
pass wordsQuantity as second argument to i18.t() and modifiy texts.js variable with {{}}

2022-01-26 12:26 UTC, fperezboco commented on src/app/screens/Bloc/index.js
> +    if (textStyle === 'bold') setBold(!bold);
move all this 'bold', 'italic', etc. constants to a general constants file, import it and use like NOTEBLOC_ACTIONS.BOLD

2022-01-26 12:26 UTC, fperezboco commented on src/app/screens/History/components/NoteItem/index.js
> +  const deleteNoteLoading = useSelector(state => state.notes.deleteNoteLoading);
move this to the bottom of the file

```
import { createSelector } from 'reselect';
...
export const loadingSelector = createSelector(
  store => store.notes.deleteNoteLoading,
  (deleteNoteLoading) => deleteNoteLoading
);


const mapStateToProps = state => ({
  loading: loadingSelector(state)
});
```
anyways, as we have 1 loading variable, a selector is not necessary here

2022-01-26 12:26 UTC, fperezboco commented on src/app/screens/History/components/NoteItem/utils.js
> +      ? `Los campos ${{ ...fields }} estan vacios, desea salvar la nota asi?`
move to constants. Is this used?

2022-01-26 12:26 UTC, fperezboco commented on src/app/screens/History/index.js
> +      <NotesContainer notes={useSelector(state => state.notes)} />
avoid useSelector

2022-01-26 12:26 UTC, fperezboco commented on src/app/screens/History/index.js
> +  const getNotesFromAPI = useCallback(() => dispatch(NotesActions.getNotes()), [dispatch]);
why a callback here? dispatch won't change

2022-01-26 12:26 UTC, fperezboco commented on src/app/screens/History/index.js
> +  }, [getNotesFromAPI]);
why [getNotesFromAPI]? this executes on mount but you could use []

2022-01-26 12:26 UTC, fperezboco commented on src/app/screens/History/components/NotesContainer/index.js
> +        <UTLabel className={styles.notesContainerEmptyMsg} medium gray>
we don't abbreviate, I would rename it to emptyMessageContainer

2022-01-26 12:26 UTC, fperezboco commented on src/app/screens/History/components/NotesContainer/index.js
> +    <div className={styles.spinnerContainer}>
Not a requested change, but you can use UTLoading from energy UI! it receives loading={bool} as prop.

2022-01-26 12:26 UTC, fperezboco commented on src/app/screens/History/components/NotesContainer/index.js
> +import UTLabel from '@widergy/energy-ui/dist/components/UTLabel';
import { UTLabel } from '@widergy/energy-ui'

2022-01-26 12:26 UTC, fperezboco commented on src/redux/notes/actions.js
> +  deleteInRedux: payload => ({ type: actions.DELETE_IN_REDUX, payload })
indeed!

2022-01-26 18:03 UTC, facu-rodriguez requested changes
Nice work Abot! I reaaly like how it is turning out!

Some comments: 

- Check this: When trying to go into /history view
![Captura de pantalla de 2022-01-26 14-47-06](https://user-images.githubusercontent.com/68086087/151218073-9dc46eb1-4320-4e26-a389-48d36bf300b9.png)


----------------------------------------------

- I believe the experience when saving a note it is a little weird. I'ld add some source of visual indicator (like a "loading" toast using the provider you made!) because after saving a note the user sees all the buttons going on disabled and doesn't know why

https://user-images.githubusercontent.com/68086087/151218295-ab121a91-5f9b-4479-adac-ae740c53e4ad.mp4

-----------------------------------------------

- This shouldn't happen


https://user-images.githubusercontent.com/68086087/151219141-6631aaa4-35c2-4faf-bb03-46740e26c754.mp4

2022-01-26 18:03 UTC, facu-rodriguez commented on src/app/components/InlineTextArea/styles.module.scss
> +  font-size: $large * 2;
remember to define a exact size!

2022-01-26 18:03 UTC, facu-rodriguez commented on src/app/components/Topbar/index.js
> +  disableButtons: state.notes.notesLoading || state.notes.saveNoteLoading || state.notes.deleteNoteLoading
change this prop name with -> 'loading'

2022-01-26 18:03 UTC, facu-rodriguez commented on src/app/components/Topbar/index.js
> +  disableButtons: state.notes.notesLoading || state.notes.saveNoteLoading || state.notes.deleteNoteLoading
also, we could make a selector loading!

2022-01-26 18:03 UTC, facu-rodriguez commented on src/app/screens/History/components/NotesContainer/index.js
>  import React from 'react';
check the constants.js file in this component folder. It is empty, we should delete empty files!

2022-01-26 18:03 UTC, facu-rodriguez commented on src/app/screens/History/index.js
> +import { connect, useDispatch } from 'react-redux';
Since we are a using a connect function on this component, we should add "dispatch" as a prop in the component and using it directly. Delete the useDispatch

2022-01-26 18:03 UTC, facu-rodriguez commented on src/app/screens/History/index.js
> +  const dispatch = useDispatch();
About my comment above 

```suggestion
const History = ({ notes, dispatch }) => {
```

2022-01-26 18:03 UTC, facu-rodriguez commented on src/constants/notepadActions.js
> +  bold: 'bold',
I'm not sure about it, but there is no need to have two constants with the same value (nevermind that one is Uppercase and the other in lower case).

Try leaving only the uppercasse constants and let me know if it doesn't work!

2022-01-27 16:22 UTC, fperezboco approved these changes
Excellent job Abot! 2 tiny minor details, approved but fix them before Facu's approve

2022-01-27 16:22 UTC, fperezboco commented on src/app/components/Topbar/index.js
> +          Cargando...
Move to constants

2022-01-27 16:22 UTC, fperezboco commented on src/app/components/Topbar/index.js
> +// import {} from '@widergy/energy-ui';
Remove comment

2022-01-27 18:30 UTC, facu-rodriguez approved these changes
Nice work Abot!!

2022-01-27 18:30 UTC, facu-rodriguez commented on src/redux/notes/selectors.js
> +);
Update this on Redux forms pr

```suggestion
export const loadingSelector = createSelector(
  state => state.notes.notesLoading,
  state => state.notes.saveNoteLoading,
  state => state.notes.deleteNoteLoading,
  (notesLoading, saveNoteLoading, deleteNoteLoading) => notesLoading || saveNoteLoading || deleteNoteLoading
);
```

2022-01-28 12:13 UTC, merged