Adding form
lucasabot/bloc-de-notas pull request #5
Opened 2022-01-27 20:06 UTC by lucasabot

# Work in progress

2022-01-28 13:14 UTC, facu-rodriguez requested changes
Nice work!!

Checkout this:



https://user-images.githubusercontent.com/68086087/151552952-d4285c5a-fec3-491d-a407-16f88595c54b.mp4

2022-01-28 13:59 UTC, facu-rodriguez requested changes
For now see this. Please resolve conflicts and merge the release, then I'll see it

We shouldn't be able to save a note that hasn't differences with the one saved on the store/services:

https://user-images.githubusercontent.com/68086087/151556285-a41545a3-2507-42b6-93af-3b9518a5f29b.mp4

---------------------------------------

- Phone number validation is working a bit weird. If the first number is a "0" validations breaks:

https://user-images.githubusercontent.com/68086087/151557325-e3126afb-17ca-4e53-9dda-9bffe0bc5a07.mp4

2022-01-28 16:31 UTC, fperezboco requested changes
Excellent job with Forms Abot!! they work great! just some tiny details to consider.

---

Fields are not centered
![image](https://user-images.githubusercontent.com/78354349/151583754-5161e331-0596-4e33-9eb3-61a3fb9af82e.png)

---

- Validation errors should be in spanish.
- Add a loading, wrap the entire form with UTLoading when the survey is sent
- When you leave the field, it get's validated. In widergy we validate only after submit. Check if it's not too complex to do that. For example, validation looks weird when adding spaces, so if validated on submit, it would be a bit more tidy. The rest works great!

2022-01-28 16:43 UTC, fperezboco requested changes
Check you have key problems
![image](https://user-images.githubusercontent.com/78354349/151585763-929611f3-4f12-4340-bf08-9e65ff7251cd.png)

2022-01-28 16:43 UTC, fperezboco commented on src/app/components/InputForm/components/SurveyField/index.js
> +        className={`${className} ${touched && (error || warning) ? styles.inputFormError : ''}`}
```suggestion
        className={`${className} ${touched && (error || warning) && styles.inputFormError}`}
```
`''` Is not necessary

2022-01-28 16:43 UTC, fperezboco commented on src/app/components/ReduxForm/index.js
> +          <InputForm
Can't you use `Field` directly here? why you need `InputForm`?
```suggestion
          <Field
```

2022-01-28 16:43 UTC, fperezboco commented on src/app/components/ReduxForm/styles.module.scss
> +}
add a new line here

2022-01-28 16:43 UTC, fperezboco commented on src/app/components/ReduxForm/utils.js
> +const numbers = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'];
move to constants

2022-01-28 16:43 UTC, fperezboco commented on src/app/components/ReduxForm/utils.js
> +  value.length < 10 || !validateCharacters(numbers, value)
move 10 to constants

2022-01-28 16:43 UTC, fperezboco commented on src/app/components/ReduxForm/utils.js
> +    ? 'Invalid phone number, must be 10 digits'
move to texts, use spanish as the rest of the app

2022-01-28 16:43 UTC, fperezboco commented on src/app/screens/Survey/styles.module.scss
> +}
add new line

2022-01-28 19:40 UTC, facu-rodriguez requested changes
You almost have it!

Saving validation isn't working as expected yet!

https://user-images.githubusercontent.com/68086087/151610668-ef4bf38a-eb2b-491e-a09d-22bfb3059689.mp4

----------------------------------

- I can't save or cancel the form
 

https://user-images.githubusercontent.com/68086087/151610980-b3831a23-5fa7-4276-92a9-3b549942aed9.mp4

2022-01-28 19:40 UTC, facu-rodriguez commented on src/app/components/InputForm/components/SurveyField/index.js
> +        rows={ALTERNATIVE_INPUT_TYPES.textarea.rows}
destructure ALTERNATIVE_INPUT_TYPES props

2022-01-28 19:40 UTC, facu-rodriguez commented on src/app/components/InputForm/components/SurveyField/constants.js
> +  textarea: { type: 'textarea', rows: '10', cols: '30' }
use camel case
```suggestion
  textArea: { type: 'textarea', rows: '10', cols: '30' }
```

2022-01-28 19:40 UTC, facu-rodriguez commented on src/app/components/ReduxForm/constants.js
> +export const TEXTAREA_ROWS = 30;
extract this constants into a constants.js file inside src/constants/yourFile.js and then import these values into this file and into InputForm/Components/SurveyField/constants.js file too

2022-01-28 19:40 UTC, facu-rodriguez commented on src/app/components/ReduxForm/styles.module.scss
> +}
```suggestion
%baseStyles {
  border: 0;
  border-bottom: 1px solid $gray;
  font-family: 'Poppins', sans-serif;
  font-size: $large !important;
  margin: 10px;
  resize: none;
  width: 450px;
  
  &:focus {
    border: none;
  border-bottom: 1px solid $primary-button;
  font-family: 'Poppins', sans-serif;
  outline: none !important;
  resize: none;
  }
}

.formInput {
  @extend %baseStyles;
  margin: 10px;
  width: 450px;
}


.formInput[type=number]::-webkit-outer-spin-button,
.formInput[type=number]::-webkit-inner-spin-button {
  -webkit-appearance: none !important;
  margin: 0 !important;
}
```

2022-01-28 19:40 UTC, facu-rodriguez commented on src/app/components/ReduxForm/styles.module.scss
> +}
with the suggested change above this wouldn't be longer necessary

2022-01-28 19:40 UTC, facu-rodriguez commented on src/app/components/ReduxForm/utils.js
> +  value && !/([A-Z])$/i.test(value) ? 'Invalid name, must be just characters.' : undefined;
Move this too into the text file and also, as Fede suggested, use Spanish!

2022-01-28 19:40 UTC, facu-rodriguez commented on src/app/components/Topbar/styles.module.scss
> +    justify-content: space-evenly;
this isn't longer necessary

2022-01-28 19:40 UTC, facu-rodriguez commented on src/app/screens/History/components/NoteItem/index.js
> +        }
move the validation into a const.
`const validationToSave :  textValue?.length > 0 && titleValue?.length > 0 && hasDifferences(note, { content: textValue, title: titleValue, italic, bold })`

```suggestion
        canSave={ validationToSave }
```

2022-01-28 19:40 UTC, facu-rodriguez commented on src/redux/notes/selectors.js
> +  (notesLoading, saveNoteLoading, deleteNoteLoading) => notesLoading || saveNoteLoading || deleteNoteLoading
:100: :rocket:

2022-01-31 18:44 UTC, fperezboco approved these changes
:ok_hand: works nice! Good Job!! :rocket: :rocket: :rocket: :rocket:

2022-01-31 19:43 UTC, facu-rodriguez requested changes
Almost theeeeereeee.

Just check this:

https://user-images.githubusercontent.com/68086087/151859655-953db95a-1e2b-4fbc-b46a-0f2ca17549f0.mp4

2022-02-01 17:34 UTC, facu-rodriguez requested changes
2 "pavadas" and we are done

2022-02-01 17:34 UTC, facu-rodriguez commented on src/app/components/Topbar/styles.module.scss
> +  } */
delete this

2022-02-01 17:34 UTC, facu-rodriguez commented on src/app/components/Topbar/styles.module.scss
>  }
add an empty line

2022-02-01 17:34 UTC, facu-rodriguez commented on src/app/components/Topbar/styles.module.scss
> +    margin: 0px 1px;
There is no need to change this now, but you should know that linter wouldn't let you commit when having a 0 value with the unit defined
```suggestion
    margin: 0 1px;
```

2022-02-01 17:38 UTC, facu-rodriguez approved these changes
Well done!

2022-02-01 17:39 UTC, merged